version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: notification_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  notification-api:
    build:
      context: ./notification-api
    container_name: notification-api
    depends_on:
      - kafka
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/notification_system
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"

  notification-worker:
    build:
      context: ./notification-worker
    container_name: notification-worker
    depends_on:
      - kafka
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_GROUP: notification-workers
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKER_RETRY_MAX_ATTEMPTS: 3
      WORKER_RETRY_BACKOFF_MS: 500
      WORKER_PROVIDER_TIMEOUT_MS: 3000
      WORKER_PROVIDER_EMAIL_URL: ""
      WORKER_PROVIDER_SMS_URL: ""
      WORKER_PROVIDER_PUSH_URL: ""
    ports:
      - "8082:8082"
