server:
  port: 8082

spring:
  application:
    name: notification-worker

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: notification-workers
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 10
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.sahil.notification.model.NotificationEvent

    listener:
      ack-mode: manual
      concurrency: 3

  data:
    redis:
      host: localhost
      port: 6379

worker:
  retry:
    max-attempts: 3
    backoff-ms: 500

  providers:
    timeout-ms: 3000
    email:
      url: ""
    sms:
      url: ""
    push:
      url: ""
